python plot_rpca_all.py --file-dir synthetic_data_mixed --file-name B5_noise0.05_p0.05
python plot_rpca_all.py --file-dir synthetic_data_mixed --file-name B10_noise0.05_p0.05
python plot_rpca_all.py --file-dir synthetic_data_mixed --file-name B20_noise0.05_p0.05
python plot_rpca_all.py --file-dir synthetic_data_twoblock --file-name B5_noise0.05_p0.05
python plot_rpca_all.py --file-dir synthetic_data_twoblock --file-name B10_noise0.05_p0.05
python plot_rpca_all.py --file-dir synthetic_data_twoblock --file-name B20_noise0.05_p0.05
#python plot_rpca_all.py --file-dir synthetic_data_realdata --file-name B20_noise0.05_FIMMnoise0.0
python plot_rpca_all.py --file-dir synthetic_data_realdata --file-name B20_noise0.05_FIMMnoise0.01
python plot_rpca_all.py --file-dir synthetic_data_realdata --file-name B20_noise0.05_FIMMnoise0.02
python plot_rpca_all.py --file-dir synthetic_data_realdata --file-name B20_noise0.05_FIMMnoise0.005
